[package]
name = "piston2d_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "1.0.0"
piston_window = "0.132.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
rand = "0.9.0"
